name = "Linkita"
description = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
license = "MIT"
homepage = "https://codeberg.org/salif/linkita"
min_version = "0.19.0"
demo = "https://salif.github.io/linkita/en/"
tags = ["Blog", "Multilingual", "Responsive", "SEO", "Search"]

[author]
name = "Salif Mehmed"
homepage = "https://salif.eu"

[original]
author = "st1020"
homepage = "https://st1020.com"
repo = "https://github.com/st1020/kita"
